import numpy as np
import argparse
import sys
from pathlib import Path
from exec_sim import exec_fp16_sum, exec_fp32_sum, exec_fp64_sum

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from adder_model.pp_functions import bits_to_float

def exec_fused_sum(i1, i2, i3, i4, intermediate_dtype=np.float16):
    """
    computes the sum of 4 operands using a parametrized intermediate precision,
    then casts the final result back to FP16.
    """

    operands = np.array([i1, i2, i3, i4], dtype= intermediate_dtype)

    total_sum = np.sum(operands)

    # Cast back to original dtype, "packing" of result 
    return np.float16(total_sum)


def parse_arguments():
    parser = argparse.ArgumentParser(
        usage="give the four arguments by terminal or provide an input file containing the data in hex format",
        description="Generate the golden reference for a 4 operand FP16 adder"
    )

    parser.add_argument(
        "-i", "--input_file",
        required=False,
        help="Path to the hex input file generated by the automation script. The file must contain lines of 16 hex encoded values representing 4 FP16 operands. If a file is not provided the script will query the user for 4 operands via terminal"
    )

    parser.add_argument(
        "--gen_assert_signals",
        action="store_true",
        help="Flag to save the expected internal signals to a file."
    )

def main():
    args = parse_arguments()

    if (args.input_file): # Multiple inputs -> Multiple simulations
        try:
            with open(args.input_file, 'r') as f:
                # each line contains 64 bits of data -> 4 FP16 operands
                lines = f.readlines()
        except FileNotFoundError:
            print(f"ERROR: Could not find input file @ {args.input_file}")
            exit(1)

        for line in lines:
            # remove whitespaces and EOL characters
            clean_line = line.strip()

            assert(clean_line) # line isn't empty

            operands_bits = list(int(clean_line[i: i+4], 16) for i in range(0, 16, 4))

            num1 = bits_to_float(operands_bits[0])
            num2 = bits_to_float(operands_bits[1])
            num3 = bits_to_float(operands_bits[2])
            num4 = bits_to_float(operands_bits[3])

            exec_sim(num1, num2, num3, num4)

    else:
        # single input -> single simulation
        # no silencing of prints
        print("-"*50+"\n")
        num1 = float(input("Ingrese el primer número flotante: "))
        num2 = float(input("Ingrese el segundo número flotante: "))
        num3 = float(input("Ingrese el tercer número flotante: "))
        num4 = float(input("Ingrese el cuarto número flotante: "))

        exec_sim(num1, num2, num3, num4, monitor)