from mod_sumador import main as exec_sim
from pp_functions import float_to_bits, bits_to_float
import argparse
import sys
import os


def parse_arguments():
    parser = argparse.ArgumentParser(
        prog="Run the simulation of a 4 operand FP16 adder",
        description="Bit-accurate simulation of a 4-operand FP16 adder."
    )

    parser.add_argument(
        "-i", "--input_file",
        usage="The file must contain lines of 16 hex encoded values representing 4 FP16 operands. If a file is not provided the script will query the user for 4 operands via terminal",
        required=False,
        help="Path to the hex input file generated by the automation script."
    )

    parser.add_argument(
        "-o", "--output_file",
        required=False,
        help="Path to dump the expected outputs for the TB."
    )

    parser.add_argument(
        "--gen_assert_signals",
        action="store_true",
        help="Flag to save the expected internal signals to a file."
    )

    parser.add_argument(
        "-d", "--debug", 
        action="store_true",
        default=False,
        help="Print to terminal internal signals."
    )

    return parser.parse_args()

def main():
    
    args = parse_arguments()
    debug_en = args.debug

    # Assert lists
    assert_aligned_mantissas, assert_signed_mantisas_w_ovf, assert_signs, assert_XOR_signs = [], [], [], []
    assert_save, assert_carry = [], []

    if (args.input_file): # Multiple inputs -> Multiple simulations

        # Silence simulation output to terminal
        if not debug_en:
            sys.stdout = open(os.devnull, 'w')

        try:
            with open(args.input_file, 'r') as f:
                # each line contains 64 bits of data -> 4 FP16 operands
                lines = f.readlines()
        except FileNotFoundError:
            print(f"ERROR: Could not find input file @ {args.input_file}")
            exit(1)

        for line in lines:
            # remove whitespaces and EOL characters
            clean_line = line.strip()

            assert(clean_line) # line isn't empty

            operands_bits = list(int(clean_line[i: i+4], 16) for i in range(0, 16, 4))

            num1 = bits_to_float(operands_bits[0])
            num2 = bits_to_float(operands_bits[1])
            num3 = bits_to_float(operands_bits[2])
            num4 = bits_to_float(operands_bits[3])

            exec_sim(num1, num2, num3, num4)

    else:
        # single input -> single simulation
        # no silencing of prints
        print("-"*50+"\n")
        num1 = float(input("Ingrese el primer número flotante: "))
        num2 = float(input("Ingrese el segundo número flotante: "))
        num3 = float(input("Ingrese el tercer número flotante: "))
        num4 = float(input("Ingrese el cuarto número flotante: "))

        exec_sim(num1, num2, num3, num4)


    if (args.gen_assert_signals):
        pass
        # parsear dict the listas, escribir a distintos archivos, nombres hardcodeados.
    
    if (args.output_file):
        pass
        # escribir a archivo resultados de simulador

    

if __name__ == "__main__":   main()
